### ISSUE TITLE
Path to Publication: Phase One

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#370]
Hi everyone,
I have some exciting news -- @cgreene spoke with the Editor in Chief at _mSystems_, and they are willing to review our manuscript, and then (if it is accepted) they will periodically review updates. This would allow us to have a "version of record" in _mSystems_, as well as the most recent updates available on GitHub. With this approach, we can share what we have so far but continue to update as more information becomes available.

We would like to have this in a version that we can submit by **July 31**. In my opinion, the best approach would be iterative -- let's try to get the most critical information filled in, and then we can work on making sure all of the ideas connect. I put up a trial run of what this would loook like for the hydroxychloroquine section, which had contributions from a large number of authors, in #369-- please take a look if you want to get a sense of how I'm picturing we can take content added by lots of different people unify it into a cohesive story. But right now, getting the information is the most important next step.

At present, these are the most urgent needs that I see:
**1. Intro: Expand the background** (immunology, all fields)
  - [ ] Right now we in desperate need of immunological background. See #349 for an effort to get this started, but feedback and contributions from people with strength in this area would be hugely valuable.
  - [ ] There are questions throughout the manuscript that may or may not be relevant. In line with your own expertise, please submit PRs answering, moving or removing these questions if you think they would be better addressed elsewhere.

**2. Therapeutics: Rationale behind each drug class** (pharmacology)
  - [ ] For this first version, we will include examples from several different drug classes (e.g., broad-spectrum pharmaceuticals, biologics, etc.) We need to flesh out the background about what these classes mean

**3. Diagnostics: Serological Tests** (pharmacology, immunology)
  - [ ] There is more info to add about testing for antibodies in people who recover from COVID-19 would work, what has been attempted, and what may or may not be possible given the current information available

**4. Intro: Add in figures** (public health, computational fields)
  - There are some places where Manubot-based figures may be appropriate, so that they will update (e.g., a graph of worldwide COVID-19 cases in the intro). There are two parts to this:
      - [ ] Locate data source(s) online
      - [ ] Figure out how to integrate data with Manubot functionalities

Additionally, anyone & everyone can help this push by reading through the manuscript and flagging anything you find confusing or where there isn't sufficient context to understand. Given the [scope of this journal](https://msystems.asm.org/content/scope), we need to make sure there is sufficient background for readers from broad academic backgrounds to understand the arguments. Please comment below with ideas, open new issues, or best of all, open PRs to fix the problems you identify!

Additional suggestions, comments, questions welcome below! There is a lot of restructuring that needs to happen before we can submit, but for now let's prioritize getting information filled in.

**PRs addressing these topics will receive highest priority for review. If you are working on a PR outside the scope of the current manuscript, please have it ready for review by 6/30/2020 -- PRs addressing new topics will be tabled until after we submit**

**Comment by rdvelazquez** [comment]
This sounds great! I can try and help with 4.

**Comment by rando2** [comment]
It seems we are now in July, so need to shift our focus to bringing all the content we have together!
There are a few updates that we still need (in addition to what is outlined above)--
- [ ] Update tocilizumab with new study (#464)
- [ ] Add dexamethasone (since this one is surprisingly promising!) #398 
- [ ] Add mortality rates to pathogenesis (per discussion in #349)

**Comment by qiyanjun** [comment]
Sorry for getting input late. I will add a few machine-learning-based papers on COVID19 data (by this week). Will a section on the topic too late for Phase I?

**Comment by qiyanjun** [comment]
Is adding AI-based solutions of interest to the Phase-I submission?

**Comment by rando2** [comment]
> Is adding AI-based solutions of interest to the Phase-I submission?

That would be something extremely interested to look at, but perhaps better suited to the first update (approximately October or November, we hope!) We do have some computational biology text under review (#347) but it's not quite all the way to AI.

**Comment by jharenza** [comment]
Hi @rando2! I added new issues #500 and #501, but @cgreene suggested those can be added during the second iteration of the manuscript. I read through the above missing information and think I can help with 3. 

Question about scope: Are we focusing on testing in the U.S. (I see the FDA-approved test mentioned)? According to the WHO website, there are 100s of immunoassays for COVID-19 antibody detection.
Question about content: For any test I find to discuss, should I add it as an issue, similar to how the papers are being added, or compile and add them in one issue, or just add them in the text? Eg: [CDC serology test](https://www.cdc.gov/coronavirus/2019-ncov/lab/serology-testing.html) and [Quest serology test](https://www.questdiagnostics.com/home/Covid-19/HCP/antibody/) for exposure. 

Thanks!
