### ISSUE TITLE
New Paper (Therapeutic): COVID-19 Treatment and Vaccine Tracker

### ISSUE THREAD

**Issue by agitter** [greenelab/covid19-review#74]
Title: COVID-19 Treatment and Vaccine Tracker

## Please paste a link to the paper or a citation here:

Link: https://milkeninstitute.org/sites/default/files/2020-03/Covid19%20Tracker%20NEW3-24-20-REVISED.pdf

## What is the paper's [DOI](https://library.uic.edu/help/article/1966/what-is-a-doi-and-how-do-i-use-them-in-citations)?

DOI: N/A

## Please list some keywords (3-10) that help identify the relevance of this paper to COVID-19

* clinical trials
* treatments
* vaccines
* FDA approval status

## Which areas of expertise are particularly relevant to the paper? 

- [ ] virology
- [ ] epidemiology
- [ ] biostatistics
- [ ] immunology
- [x] pharmacology

### Please provide 1-2 sentences introducing the study and its main findings
This is not a full paper but rather a spreadsheet from the Milken Institute listing COVID-19 treatments and vaccines in development.  It provides links to original sources.

#### What is the sample size? If multiple groups are considered, give sample size for each group (including controls).

* number treated with treatment A
* number treated with treatment B

##### What other specific inclusion-exclusion criteria are considered?

For example, do the investigators exclude patients with diagnosed neoplasms or patients over/under a certain age?

#### How are treatments assigned?

For example, is it an interventional or an observational study?

#### Is the study randomized?

A study can be interventional but not randomized (e.g., a phase I or II clinical trial is interventional but often not randomized).

#### Provide other relevant details about the design.

This includes possible treatment stratification (e.g., within litters for animal studies, within hospitals for human studies), possible confounding variables (e.g., having a large age range of individuals), possible risks of bias and how they are addressed (e.g., is there masking in a clinical trial? how are individuals chosen in an observational study?).

#### Describe the outcome that is assessed and whether it is appropriate.

For example: Is the outcome assessed by a clinician or is it self-reported?
Is the outcome based on viral load or a functional measurement (e.g., respiratory function, discharge from hospital)?
What method is used to measure the outcome?
How long after a treatment is the outcome measured?

#### Are outcome measurements complete?

For example, are there individuals lost to follow up?

#### Are outcome measurements subject to various kinds of bias?

For example, a lack of masking in randomized clinical trials.

#### What methods are used for inference?

For example, logistic regression, nonparametric methods.

#### Are the methods appropriate for the study?

For example, are clustered data treated independently or are clusters adjusted for, such as different hospitals or litters?

#### Are adjustments made for possible confounders?

For example, adjustment for age, sex, or comorbidities.

#### What is the estimated association?

For example, is it an estimated odds ratio, a median difference in detected cases, etc?

#### What measures of confidence or statistical significance are provided?

For example, confidence intervals, p-values, and/or Bayes factors.

#### Can we make a causal interpretation for the individuals in the study of drug -> outcome, such as "taking drug A improves likelihood of survival twofold over taking drug B."

For example, with a well-performed animal study or randomized trial it is often possible to infer causality.
If is an observational study, does it match up with some of the Bradford Hill criteria? https://www.edwardtufte.com/tufte/hill https://en.wikipedia.org/wiki/Bradford_Hill_criteria

#### Are there identified side effects or interactions with other drugs?

For example, is the treatment known to cause liver damage or to not be prescribed for individuals with certain comorbities?

#### Are there specific subgroups with different findings?

For example, do individuals with a specific baseline seem to do particularly well? Be particularly cautious with respect to multiple testing here.

#### If the study is an animal study, which animal and how relevant is that model?

Is the model system appropriate? Is there evidence from past use that it's highly-relevant to therapeutic design in this context?

#### If it is a human study, what characteristics of the study population may support/limit extrapolation?

* Can results extrapolate easily to other similar groups? (e.g., same country, similar age groups)
* What would happen if conditions are extended in terms of dose or duration?
* Can results be extrapolated to other populations or in very different settings? (e.g., different age group, primary care setting vs emergency department etc)

### Summary of reliability

1-2 sentences on concluding remarks, including summary of strengths, weaknesses, limitations.

### Progress

_Check off the components as they are completed. If the component is not applicable, check the box as well._

- [ ] 1-2 sentences introducing the study and its main findings
- [ ] Describe How many/what drugs/combinations are being considered 
- [ ] Describe the model system
- [ ] What is the sample size? 
- [ ] What countries/regions are considered 
- [ ] What is the age range, gender, other relevant characteristics 
- [ ] Describe study setting 
- [ ] Describe  other specific inclusion-exclusion criteria 
- [ ] Describe how treatments are assigned
- [ ] Describe randomization (or not) and other relavent details about the design
- [ ] Describe the outcome that is assessed and whether it is appropriate.
- [ ] Describe whether the outcome measurements are complete
- [ ] Are outcome measurements subject to various kinds of bias?
- [ ] Describe methods used for inference
- [ ] Describe whether the methods are appropriate for the study
- [ ] Are adjustments made for possible confounders?
- [ ] Describe the estimated association
- [ ] What measures of confidence or statistical significance are provided?
- [ ] Describe whether a causal interpretation can be made
- [ ] Are there identified side effects or interactions with other drugs?
- [ ] Are there specific subgroups with different findings?
- [ ] If the study is an animal study, which animal and how relevant is that model?
- [ ] If it is a human study, what characteristics of the study population may support/limit extrapolation?
- [ ] Summary of reliability
